/**
 * Module 04: Structure Memory Alignment, Padding, and Packing
 *
 * Concepts demonstrated:
 * 1. Struct padding generated by compiler for memory word alignment.
 * 2. Field reordering to minimize memory footprint.
 * 3. Inspecting member offsets with offsetof().
 * 4. Packed structs for binary protocols (#pragma pack).
 */

#include <stdio.h>
#include <stdint.h>
#include <stddef.h> // for offsetof
#include <string.h>

/* Naive layout: Excessive padding between fields */
struct UnalignedExample {
    char a;      // 1 byte  (+ 3 bytes padding)
    int32_t b;   // 4 bytes
    char c;      // 1 byte  (+ 7 bytes padding if 64-bit aligned)
    int64_t d;   // 8 bytes
};

/* Optimized layout: Sorted from largest alignment requirement to smallest */
struct OptimizedExample {
    int64_t d;   // 8 bytes
    int32_t b;   // 4 bytes
    char a;      // 1 byte
    char c;      // 1 byte (+ 2 bytes trailing padding to make total multiple of 8)
};

/* Packed struct: Zero padding (useful for raw network packets / file headers) */
#pragma pack(push, 1)
struct PackedExample {
    char a;      // 1 byte
    int32_t b;   // 4 bytes
    char c;      // 1 byte
    int64_t d;   // 8 bytes
};
#pragma pack(pop)

/* Helper: Dump raw bytes of a memory block with offset markers */
void dump_struct_bytes(const char *name, const void *ptr, size_t size) {
    const uint8_t *bytes = (const uint8_t *)ptr;
    printf("--- %s (Total size: %zu bytes) ---\n", name, size);
    printf("Offset: ");
    for (size_t i = 0; i < size; i++) {
        printf("%02zu ", i);
    }
    printf("\nBytes:  ");
    for (size_t i = 0; i < size; i++) {
        printf("%02X ", bytes[i]);
    }
    printf("\n\n");
}

int main(void) {
    printf("====================================================\n");
    printf(" 1. STRUCT SIZES & MEMORY OVERHEAD                  \n");
    printf("====================================================\n");
    printf("Sum of raw member sizes   : 1 + 4 + 1 + 8 = 14 bytes\n");
    printf("sizeof(struct UnalignedExample): %zu bytes\n", sizeof(struct UnalignedExample));
    printf("sizeof(struct OptimizedExample): %zu bytes (Memory saved!)\n", sizeof(struct OptimizedExample));
    printf("sizeof(struct PackedExample)   : %zu bytes (Exact match, 0 padding)\n\n", sizeof(struct PackedExample));

    printf("====================================================\n");
    printf(" 2. MEMBER OFFSETS (offsetof macro)                 \n");
    printf("====================================================\n");
    printf("UnalignedExample:\n");
    printf("  offsetof(a) = %zu\n", offsetof(struct UnalignedExample, a));
    printf("  offsetof(b) = %zu (Gap of %zu bytes after 'a')\n",
           offsetof(struct UnalignedExample, b),
           offsetof(struct UnalignedExample, b) - sizeof(char));
    printf("  offsetof(c) = %zu\n", offsetof(struct UnalignedExample, c));
    printf("  offsetof(d) = %zu (Gap of %zu bytes after 'c')\n\n",
           offsetof(struct UnalignedExample, d),
           offsetof(struct UnalignedExample, d) - (offsetof(struct UnalignedExample, c) + sizeof(char)));

    printf("OptimizedExample:\n");
    printf("  offsetof(d) = %zu\n", offsetof(struct OptimizedExample, d));
    printf("  offsetof(b) = %zu\n", offsetof(struct OptimizedExample, b));
    printf("  offsetof(a) = %zu\n", offsetof(struct OptimizedExample, a));
    printf("  offsetof(c) = %zu\n\n", offsetof(struct OptimizedExample, c));

    printf("====================================================\n");
    printf(" 3. VISUALIZING RAW PADDING BYTES                   \n");
    printf("====================================================\n");
    struct UnalignedExample unaligned;
    // Fill with sentinel 0xAA pattern to clearly see untouched padding bytes
    memset(&unaligned, 0xAA, sizeof(unaligned));
    unaligned.a = 'X';       // 0x58
    unaligned.b = 0x11223344;
    unaligned.c = 'Y';       // 0x59
    unaligned.d = 0x0102030405060708LL;

    dump_struct_bytes("struct UnalignedExample (0xAA indicates padding)", &unaligned, sizeof(unaligned));

    return 0;
}
